// <auto-generated />
using ASPStoreModernized.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPStoreModernized.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250804215016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPStoreModernized.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Description = "A stylish desk lamp for your home office. Features adjustable brightness and color temperature settings. The lamp includes a USB charging port and touch controls.",
                            ImageUrl = "",
                            InStock = true,
                            Name = "Classic Desk Lamp",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Description = "Comfortable chair with lumbar support. Fully adjustable height, armrests, and recline settings. Breathable mesh back keeps you cool during long work sessions.",
                            ImageUrl = "",
                            InStock = true,
                            Name = "Ergonomic Office Chair",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Description = "Compact keyboard with quiet keys. Connects via Bluetooth to up to 3 devices simultaneously. Includes backlit keys and a rechargeable battery that lasts up to 2 weeks.",
                            ImageUrl = "",
                            InStock = true,
                            Name = "Wireless Keyboard",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Description = "24-inch full HD display. Features ultra-thin bezels, 144Hz refresh rate, and AMD FreeSync technology. Includes HDMI, DisplayPort, and USB-C connections.",
                            ImageUrl = "",
                            InStock = true,
                            Name = "LED Monitor",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Description = "Portable speaker with rich bass. Waterproof design makes it perfect for outdoor use. Provides up to 12 hours of playback on a single charge and includes a built-in microphone for calls.",
                            ImageUrl = "",
                            InStock = true,
                            Name = "Bluetooth Speaker",
                            Price = 89.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
